import React, { Component } from 'react'

class TermsAndService extends Component{

    render(){

        return(
            <div className="container pt-5">
                <div><h3>TERMS OF SERVICE</h3><br/></div>

                <div>Please read these Terms of Service carefully as they contain important information about your 
                    legal rights, remedies, and obligations. By accessing or using the Universal Lab Platform, 
                    you agree to comply with and be bound by these Terms of Service. Your continued access or use 
                    of the Service shall be deemed your acceptance of this legal disclaimer.</div><br/><br/>

                <div>Please note: These Terms of Service contain an arbitration clause and class action waiver 
                    that applies to all Universal Orthodontic Lab Users. By accepting these Terms of Service, 
                    you agree to be bound by this arbitration clause and class action waiver. <u>Please read it carefully.</u></div><br/><br/>
            
                <div>Last Updated: October 27, 2020</div><br/><br/>

                <div>Welcome and thank you for using Universal Orthodontic Lab!</div><br/><br/>

                <div>These Terms of Service (“<b>Terms</b>“) constitute a legally binding agreement (“<b>Agreement</b>“) 
                    between you and Universal Orthodontic Lab (“<b>we</b>,” “<b>us</b>,” or “<b>our</b>“) governing your access to and 
                    use of the Universal Orthodontic Lab website, including any subdomains thereof, 
                    and any other websites through which Universal Orthodontic Lab makes its services available 
                    (collectively, “<b>Website</b>“), and application program interfaces(collectively, “<b>Application</b>“) 
                    and all associated services including information, software, product demonstration, text, displays, 
                    images, video, audio recordings, and user interfaces included in or generated by the Website, 
                    and the design, selection and arrangement thereof (collectively, “<b>Universal Lab Services</b>“). 
                    The Website, Application and Universal Lab Services together are herein after collectively referred 
                    to as the “<b>Universal Lab Platform</b>“.</div><br/><br/>

                <div>We may revise and update these Terms of Service from time to time in our sole discretion. 
                    You are expected to check this page from time to time to take notice of any changes we made, 
                    as they are binding on you. All material changes apply prospectively only. 
                    Your continued use of the Website following the posting of revised Terms of Use means that you accept 
                    and agree to the changes. When accepted by you, the revised Terms automatically revoke any license 
                    or other rights that we granted to you under the prior version.</div><br/><br/>

                <div>Our collection and use of personal information in connection with your access to and use of 
                    the Universal Lab Platform is described in our Privacy Statement.</div><br/><br/>

                <div><b>Access</b><br/>
                We reserve the right to terminate or modify the Website including any of its content, 
                in whole or in part, in any manner in our sole discretion, without notice. We will not be liable if, 
                for any reason, all or any part of the Website is unavailable at any time or for any period. 
                From time to time, we may restrict access to all or part of the Website to registered Users or 
                another subset of Users. You are solely responsible for making all arrangements necessary for 
                you to access the Website.</div><br/><br/>

                <div><b>Accounts</b><br/>
                To access portions of the Website or certain resources, you may be asked to provide certain 
                registration details or other information. It is a condition of your use of the Website, 
                and you hereby represent and warrant, that you are of the legal age of majority in the jurisdiction 
                in which you reside and that all information you provide is correct, current and complete. 
                If you choose, or you are provided with, a username, password or other information as part of our 
                security procedures, you must treat such information as confidential and you must not disclose it 
                to any third party. You agree that you are solely responsible to us for all activities identified 
                with your account. You agree to immediately notify Universal Orthodontic Lab of any unauthorized 
                use of your username or password or any other breach of security. You must logout from your account 
                at the end of each session. You should use particular caution when accessing your account from a public 
                or shared computer so that others are not able to view or record your password or other personal information. 
                Universal Orthodontic Lab has the absolute right to disable any username or password, at any time, 
                for any reason, including, if in our sole discretion we believe that you have failed to comply with 
                any provision of these Terms of Service.</div><br/><br/>

                <div><b>Payment/Terms</b><br/>
                All accounts are set up on prepaid terms. Net-15 day terms will be applied accordingly.
                Universal Orthodontic Lab reserves the right to charge you for any late fees and NSF Fees
                ($25.00 per transaction).</div><br/><br/>

                <div><b>Late Fees</b><br/>
                A three percent (3%) fee from the balance owed may be applied for every late payment.</div><br/><br/>

                <div><b>Rush Fees</b><br/>
                Case(s) requested within 1-2 days will be charged an additional $15.00 per case.</div><br/><br/>

                <div><b>Case Remakes</b><br/>
                Case(s) may be remade if the issue or concern is addressed within 90 calendar days from the initial 
                ship date. All remakes must be authorized by Universal Orthodontic Lab by submitting an RMA Form with 
                an appropriate Authorization Number. Remakes and/or requests for remakes after 90 calendar days are 
                not accepted.</div><br/><br/>

                <div><b>Appliance Fabrication Cancellations</b><br/>
                Because Universal Orthodontic Lab manufactures custom appliances, we are unable to facilitate 
                cancellation requests after production begins. We may, at our own discretion, honor such requests 
                if they are made in the first 24 hours after we receive your case or before production commences.</div><br/><br/>

                <div><b>Pickup Request</b><br/>
                Users may call to schedule a pickup as needed during business hours. Same-day pickups must be arranged 
                before 10:00am. Universal Orthodontic Lab will provide pickups at no charge. 
                Standard shipping fees will be applied after the second pickup attempt. 
                Please contact us at <a href="mailto:customerservice@uniortholab.com"> customerservice@uniortholab.com</a> for rates or for 
                additional information.</div><br/><br/>

                <div><b>User Content</b><br/>
                Universal Orthodontic Lab may, at its sole discretion, enable Users to (i) create, upload, post, send, 
                receive and store content, such as text, photos, audio, video, or other materials and information on 
                or through the Universal Lab Platform (“User Content”); and (ii) access and view User Content and 
                any content that Universal Orthodontic Lab itself makes available on or through the Universal Lab Platform, 
                including proprietary Universal Orthodontic Lab content and any content licensed or authorized 
                for use by or through Universal Orthodontic Lab from a third party (“Universal Lab Content” and together 
                with User Content,”Collective Content”).</div><br/><br/>

                <div>You are solely responsible for all User Content that you make available on or through 
                    the Universal Lab Platform. Accordingly, you represent and warrant that: (i) you either are the sole 
                    and exclusive owner of all User Content that you make available on or through the Universal Lab Platform 
                    or you have all rights, licenses, consents and releases that are necessary to grant to 
                    Universal Orthodontic Lab the rights in and to such User Content, as contemplated under these Terms; 
                    and (ii) neither the User Content nor your posting, uploading, publication, submission or transmittal 
                    of the User Contentor Universal Orthodontic Lab’s use of the User Content (or any portion thereof) 
                    will infringe, misappropriate or violate a third party’s patent, copyright, trademark, trade secret, 
                    moral rights or other proprietary or intellectual property rights, or rights of publicity or privacy, 
                    or result in the violation of any applicable law or regulation.</div><br/><br/>

                <div>You will not post, upload, publish, submit or transmit any User Content that: (i) is fraudulent, 
                    false, misleading (directly or by omission or failure to update information) or deceptive; 
                    (ii)is defamatory, libelous, obscene, pornographic, vulgar or offensive; (iii)promotes discrimination, 
                    bigotry, racism, hatred, harassment or harm against any individual or group; (iv) is violent or 
                    threatening or promotes violence or actions that are threatening to any other person or animal; 
                    (v) promotes illegal or harmful activities or substances; or (vi) violates any Universal Orthodontic Lab 
                    policy. Universal Orthodontic Lab may, without prior notice, remove or disable access to any 
                    User Content that Universal Orthodontic Lab finds to be in violation of these Terms or 
                    Universal Orthodontic Lab’s then-current Policies, or otherwise may be harmful or objectionable 
                    to Universal Orthodontic Lab, its Users, third parties, or property.</div><br/><br/>

                <div>We may, but are under no obligation to, monitor or censor comments made by Users and we are not responsible 
                    for the accuracy, completeness, appropriateness or legality of anything posted, depicted or otherwise provided 
                    by third-party users and we disclaim any and all liability relating thereto.</div><br/><br/>

                <div><b>Intellectual Property</b></div><br/><br/>

                <div><b>Website</b><br/>
                The Website in its entirety is owned by Universal Orthodontic Lab, Inc. or our licensors and is protected 
                by United States and international laws regarding copyrights, patents, trademarks, trade secrets and 
                other intellectual property or proprietary rights. You are permitted to use the Website only for legitimate 
                business purposes related to your role as a current or prospective customer, developer, partner, supplier 
                or distributor of Universal Orthodontic Lab. You shall not copy, modify, create derivative works of, 
                publicly display or perform, republish, download or store, or transmit any Website Content without 
                Universal Orthodontic Lab’s express prior written consent or except as expressly provided in these 
                Terms of Service.</div><br/><br/>

                <div><b>Universal Orthodontic Lab Technology</b><br/>
                As between Universal Orthodontic Lab and you, all rights, title, and interest in and to all intellectual 
                property rights in the Universal Orthodontic Lab Technology are owned exclusively by Universal Orthodontic 
                Lab notwithstanding any other provision in these Terms of Service. Except as otherwise expressly provided 
                in these Terms of Service, Universal Orthodontic Lab reserves all rights in the Universal Orthodontic Lab 
                Technology and does not grant you any rights, express or implied or by estoppel. As used herein, 
                “Universal Orthodontic Lab Technology” means: (a) Universal Orthodontic Lab technology and methodologies 
                (including, without limitation, products, product demonstration, software tools, hardware designs, 
                algorithms, templates, software (in source and object forms), architecture, class libraries, objects and 
                documentation) existing as of the Effective Date; (b) updates, upgrades, improvements, configurations, 
                extensions, and derivative works of the foregoing, however made, and related technical or end user 
                documentation or manuals; and (c) intellectual property anywhere in the world relating to the foregoing.</div><br/><br/>

                <div><b>Universal Orthodontic Lab Trademarks</b><br/>
                Universal Orthodontic Lab and all related, logos, product and service names, designs and slogans are 
                trademarks or service marks of Universal Orthodontic Lab or our affiliates or licensors. 
                You must not use such marks without our prior written permission. All other names, brands and marks 
                are used for identification purposes only and are the trademarks of their respective owners.</div><br/><br/>

                <div><b>User Content</b><br/>
                By creating, uploading, posting, sending, receiving, storing, or otherwise making available any User Content 
                on or through the Universal Lab Platform, you grant to Universal Orthodontic Lab a non-exclusive, worldwide, 
                royalty-free, irrevocable, perpetual (or for the term of the protection), sub-licensable and transferable 
                license to such User Content to access, use, store, copy, modify, prepare derivative works of, distribute, 
                publish, transmit, stream, broadcast, and otherwise exploit in any manner such User Content to provide and/or 
                promote the Universal Lab Platform, in any media or platform. Unless you provide specific consent, 
                Universal Orthodontic Lab does not claim any ownership rights in any User Content and nothing in these 
                Terms will be deemed to restrict any rights that you may have to use or exploit your User Content.</div><br/><br/>

                <div><b>Restrictions</b><br/>
                No right, title or interest in or to the Website including Website Content and Universal Orthodontic Lab 
                Technology, is transferred to you.<br/><br/>
                There are no implied licenses under these Terms of Service. Universal Orthodontic Lab reserves all rights 
                not expressly granted to you herein. Any use of the Website not expressly permitted by these 
                Terms of Service is a breach of these Terms of Service and may violate copyright, 
                trademark and other laws.<br/><br/>
                You shall not (and shall not permit others to) do any of the following with respect to the Website or 
                Universal Orthodontic Lab Technology: (a) license, sublicense, sell, resell, rent, lease, transfer, 
                distribute or time share it or otherwise make any of it available for access by third parties, 
                including any derivative works of Universal Orthodontic Lab Technology irrespective of which party authors 
                such derivative works; (b) use it on a production basis or with production data or use it to provide 
                services to others including services of implementation, customization or configuration of the 
                Universal Orthodontic Lab Platform without written permission; (c) disassemble, decompile or reverse 
                engineer it,particularly for the purpose of developing any product or services competitive with the 
                Universal Orthodontic Lab Platform generally; (d) subject to the preceding clause, use or access it for 
                the purpose of developing products or service competitive with the platform component of the 
                Universal Orthodontic Lab product; (e) copy, create derivative works of, or otherwise modify it, 
                except as expressly permitted hereunder; (f) disrupt its security, integrity or operation; (g) 
                remove or modify a copyright or other proprietary rights notice in it; (h) use it to reproduce, distribute, 
                display, store, transmit or use material or content protected by copyright or other intellectual property 
                right (including the rights of publicity or privacy) without first obtaining the permission of the owner; 
                (i) use it to damage the property of another; (j) use it in any manner which violates any applicable law 
                or regulation; (k) use it in a manner that temporarily or permanently alters, erases, removes, copies, 
                modifies, halts or disables any Universal Orthodontic Lab or third-party data, software or network without 
                authorization; (l) use it to create, use, send, store or run viruses or other harmful computer code; 
                (m) use it in any manner that disables, hacks or interferes with any security, digital signing, digital 
                rights management, verification or authentication mechanisms; or (n) use it in any manner that, in Universal 
                Orthodontic Lab’s reasonable judgment, circumvents the ordinary use or operation of the Universal Orthodontic 
                Lab Platform or APIs, disrupts Universal Orthodontic Lab’s pricing structure or ability to provide services 
                or support to customers, or allows any party to access Universal Orthodontic Lab Technology in excess of 
                such party’s authorized or normally intended use.<br/><br/>
                Before a User exercises any of the foregoing actions that the User believes it is entitled to, 
                the User shall provide Universal Orthodontic Lab with thirty (30) days prior written notice, or, 
                if applicable law or the relevant court order does not allow for thirty (30) days’ notice, the maximum amount 
                of notice allowable, and provide all reasonably requested information to allow Universal Orthodontic Lab 
                to assess User’s claim and, at Universal Orthodontic Lab’s sole discretion, to provide alternatives that 
                reduce any adverse impact on Universal Orthodontic Lab’s intellectual property or other rights.<br/><br/>
                Please contact Universal Orthodontic Lab if you need to make use of Universal Orthodontic Lab Technology 
                that is not permitted under these Terms of Service. Partner programs and commercial end user agreements 
                may be available to meet your needs.<br/><br/>
                If you enter into a separate agreement with Universal Orthodontic Lab that provides additional or 
                different terms with respect to Universal Orthodontic Lab Technology or its Services, then the terms of 
                that separate agreement shall control over these Terms of Service.</div><br/><br/>

                <div><b>Prohibited Activities</b><br/>
You are solely responsible for compliance with any and all laws, rules, regulations, and Tax obligations that may apply 
to your use of the Universal Lab Platform. In connection with your use of the Universal Lab Platform, you will not and 
will not assist or enable others to:<br/>

• breach or circumvent any applicable laws or regulations, agreements with third-parties, third-party rights, or our 
Terms or Policies;<br/>

• use the Universal Lab Platform or Collective Content for any commercial or other purposes that are not expressly 
permitted by these Terms or in a manner that falsely implies Universal Orthodontic Lab endorsement, partnership or 
otherwise misleads others as to your affiliation with Universal Orthodontic Lab;<br/>

• copy, store or otherwise access or use any information, including personally identifiable information about any other 
User, contained on the Universal Orthodontic Lab Platform in any way that is inconsistent with Universal Orthodontic Lab’s 
Privacy Statement or these Terms or that otherwise violates the privacy rights of Users or third parties;<br/>

• use the Universal Lab Platform in connection with the distribution of unsolicited commercial messages (“spam”);<br/>

• discriminate against or harass anyone on the basis of race, national origin, religion, gender, gender identity, physical 
or mental disability, medical condition, marital status, age or sexual orientation, or otherwise engage in any violent, 
harmful, abusive or disruptive behavior;<br/>

• misuse or abuse any services associated with the Universal Orthodontic Lab as determined by Universal Orthodontic Lab 
in its sole discretion;<br/>

• use, display, mirror or frame the Universal Lab Platform or Collective Content, or any individual element within 
the Universal Lab Platform, Universal Orthodontic Lab’s name, any Universal Orthodontic Lab trademark, logo or other 
proprietary information, or the layout and design of any page or form contained on a page in the Universal Lab Platform, 
without Universal Orthodontic Lab’s express written consent;<br/>

• dilute, tarnish or otherwise harm the Universal Orthodontic Lab brand in any way, including through unauthorized use of 
Collective Content, registering and/or using Universal Orthodontic Lab or derivative terms in domain names, trade names, 
trademarks or other source identifiers, or registering and/or using domains names, trade names, trademarks or other source 
identifiers that closely imitate or are confusingly similar to Universal Orthodontic Lab domains, trademarks, taglines, 
promotional campaigns or Collective Content;<br/>

• use any robots, spider, crawler, scraper or other automated means or processes to access, collect data or other content 
from or otherwise interact with the Universal Orthodontic Lab Platform for any purpose;<br/>

• avoid, bypass, remove, deactivate, impair, descramble, or otherwise attempt to circumvent any technological measure 
implemented by Universal Orthodontic Lab or any of Universal Orthodontic Lab’s providers or any other third party 
to protect the Universal Lab Platform;<br/>

• attempt to decipher, decompile, disassemble or reverse engineer any of the software used to provide the Universal Lab
Platform;<br/>

• take any action that damages or adversely affects, or could damage or adversely affect the performance or proper 
functioning of the Universal Lab Platform;<br/>

• export, re-export, import, or transfer the Application except as authorized by United States law, the export control 
laws of your jurisdiction, and any other applicable laws; or<br/>

• violate or infringe anyone else’s rights or otherwise cause harm to anyone.<br/><br/>

You acknowledge that Universal Orthodontic Lab has no obligation to monitor the access to or use of the Universal Lab 
Platform by any User or to review, disable access to, or edit any User Content, but has the right to do so to 
(i) operate, secure and improve the Universal Lab Platform (including without limitation for fraud prevention, 
risk assessment, investigation and customer support purposes); (ii) ensure Users’ compliance with these Terms; 
(iii) comply with applicable law or the order or requirement of a court, law enforcement or other administrative 
agency or governmental body; (iv) respond to User Content that it determines is harmful or objectionable; or (v) 
as otherwise set forth in these Terms. Users agree to cooperate with and assist Universal Orthodontic Lab in good faith, 
and to provide Universal Orthodontic Lab with such information and take such actions as may be reasonably requested by 
Universal Orthodontic Lab with respect to any investigation undertaken by Universal Orthodontic Lab or a representative of 
Universal Orthodontic Lab regarding the use or abuse of the Universal Lab Platform.<br/><br/>

If you feel that any User you interact with, whether online or in person, is acting or has acted inappropriately, 
including but not limited to anyone who (i) engages in offensive, violent or sexually inappropriate behavior, 
(ii) you suspect of stealing from you, or (iii) engages in any other disturbing conduct, you should immediately report 
such person to the appropriate authorities and then to Universal Orthodontic Lab by contacting us with your police station 
and report number (if available). You agree that any report you make will not obligate us to take any action 
(beyond that required by law, if any).<br/><br/></div>

<div><b>Disclaimers</b><br/>
Universal Orthodontic Lab cannot and does not promise or warrant that any aspect of the Website is free of viruses or 
other destructive code. You are responsible for implementing sufficient procedures and checkpoints to satisfy your 
particular requirements for anti-virus protection and accuracy of data input and output, and for maintaining a means 
external to our site for any reconstruction of any lost data. UNIVERSAL ORTHODONTIC LAB WILL NOT BE LIABLE FOR ANY LOSS 
OR DAMAGE CAUSED BY A DISTRIBUTED DENIAL-OF-SERVICE ATTACK, VIRUSES OR OTHER TECHNOLOGICALLY HARMFUL MATERIAL THAT MAY 
INFECT YOUR COMPUTER EQUIPMENT, COMPUTER PROGRAMS, DATA OR OTHER PROPRIETARY MATERIAL DUE TO YOUR USE OF THE WEBSITE 
OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE OR TO YOUR DOWNLOADING OF ANY MATERIAL POSTED ON IT, OR ON ANY WEBSITE 
LINKED TO IT.<br/><br/>

AS BETWEEN YOU AND UNIVERSAL ORTHODONTIC LAB, YOUR USE OF THE WEBSITE, DEMOS, AND ANY SERVICES OR ITEMS OBTAINED THROUGH 
THE WEBSITE, IS AT YOUR OWN RISK. THE WEBSITE, INCLUDING THE WEBSITE CONTENT, AND ANY SERVICES OR ITEMS OBTAINED THROUGH 
THE WEBSITE, ARE PROVIDED TO YOU BY UNIVERSAL ORTHODONTIC LAB ON AN “AS IS” AND “AS AVAILABLE” BASIS, WITHOUT ANY WARRANTIES 
OF ANY KIND, EITHER EXPRESS OR IMPLIED. NEITHER UNIVERSAL ORTHODONTIC LAB NOR ANY PERSON ASSOCIATED WITH UNIVERSAL 
ORTHODONTIC LAB MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY, 
SUITABILITY, ACCURACY OR AVAILABILITY OF THE WEBSITE. WITHOUT LIMITING THE FOREGOING, NEITHER UNIVERSAL ORTHODONTIC LAB 
NOR ANYONE ASSOCIATED WITH UNIVERSAL ORTHODONTIC LAB REPRESENTS OR WARRANTS THAT THE WEBSITE, INCLUDING THE WEBSITE CONTENT 
OR ANY SERVICES OR MATERIALS OBTAINED THROUGH THE WEBSITE, WILL BE ACCURATE, RELIABLE, ERROR-FREE OR UNINTERRUPTED, 
THAT DEFECTS WILL BE CORRECTED, THAT OUR SITE OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL 
COMPONENTS OR THAT THE WEBSITE OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE WILL OTHERWISE MEET YOUR NEEDS OR 
EXPECTATIONS.<br/><br/>

UNIVERSAL ORTHODONTIC LAB HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE, 
WITH RESPECT TO THE WEBSITE, THE WEBSITE CONTENT, DEMOS OR ANY SERVICES OR ITEMS OBTAIN THROUGH THE WEBSITE, INCLUDING BUT 
NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR PARTICULAR PURPOSE.<br/><br/>

 
The foregoing disclaimers apply to the maximum extent permitted by law. You may have other statutory rights. However, 
the duration of statutorily required warranties, if any, shall be limited to the maximum extent permitted by law.</div><br/><br/>

<div><b>Liability</b><br/>
EXCEPT TO THE EXTENT THAT A DISCLAIMER OF LIABILITY IS PROHIBITED UNDER APPLICABLE LAW, IN NO EVENT WILL 
UNIVERSAL ORTHODONTIC LAB, ITS AFFILIATES AND ITS LICENSORS, SERVICE PROVIDERS, EMPLOYEES, AGENTS, OFFICERS AND DIRECTORS 
BE LIABLE FOR DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE, OR INABILITY 
TO USE, THE WEBSITE, INCLUDING ANY COMMUNITY SERVICES, DEMOS, USER CONTENT, APPS, WEBSITE CONTENT OR SERVICES OR MATERIALS 
MADE AVAILABLE THROUGH THE WEBSITE, INCLUDING ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, 
INCLUDING BUT NOT LIMITED TO, PERSONAL INJURY, PAIN AND SUFFERING, EMOTIONAL DISTRESS, LOSS OF REVENUE, LOSS OF PROFITS, 
LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, LOSS OF DATA, AND WHETHER CAUSED BY TORT 
(INCLUDING NEGLIGENCE), BREACH OF CONTRACT OR OTHERWISE, EVEN IF FORESEEABLE.</div><br/><br/>

<div><b>Indemnification</b><br/>
You agree to release, defend (at Universal Orthodontic Lab’s option), indemnify, and hold Universal Orthodontic Lab and 
its affiliates and subsidiaries, and their officers, directors, employees and agents, harmless from and against any claims, 
liabilities, damages, losses, and expenses, including, without limitation, reasonable legal and accounting fees, 
arising out of or in any way connected with (i) your breach of these Terms or our Policies or Standards, 
(ii) your improper use of the Universal Orthodontic Lab Platform or any Universal Orthodontic Lab Services, 
(iii) your interaction with any User, including without limitation any injuries, losses or damages (whether compensatory, 
direct, incidental, consequential or otherwise) of any kind arising in connection with or as a result of such interaction, 
(iv) your breach of any laws, regulations or third party rights.</div><br/><br/>

<div><b>Termination</b><br/>
Universal Orthodontic Lab may terminate these Terms of Service at any time for any reason by giving you notice, 
and all licenses, permissions and other rights granted to you hereunder shall immediately terminate. Notwithstanding 
the termination of these Terms of Service for any reason, the intellectual property, disclaimers, liability, indemnification, 
dispute resolution and arbitration agreement, and general provisions sections herein shall survive.</div><br/><br/>

<div><b>Dispute Resolution and Arbitration Agreement</b><br/>

Overview of Dispute Resolution Process.<br/>

Universal Orthodontic Lab is committed to participating in a consumer-friendly dispute resolution process. 
To that end, these Terms provide for a two-part process:(1) an informal negotiation directly with Universal Orthodontic Lab’s 
customer service team,and (2) a binding arbitration administered by the American Arbitration Association (“AAA”) using 
it’s specially designed Consumer Arbitration Rules. Specifically, the Consumer Arbitration Rules provide:<br/>

• Claims can be filed with AAA online (www.adr.org);<br/>

• Arbitrators must be neutral and no party may unilaterally select an arbitrator;<br/>

• Arbitrators must disclose any bias, interest in the result of the arbitration, or relationship with any party;<br/>

• Parties retain the right to seek relief in small claims court for certain claims, at their option;<br/>

• The initial filing fee for the consumer is capped at $200;<br/>

• The consumer gets to elect the hearing location and can elect to participate live, by phone, video conference, or, 
for claims under $25,000, by the submission of documents;<br/>

• The arbitrator can grant any remedy that the parties could have received in court to resolve the party’s individual 
claim.<br/><br/>

 
Pre-Arbitration Dispute Resolution and Notification.<br/><br/>

Prior to initiating an arbitration, you and Universal Orthodontic Lab each agree to notify the other party of the dispute 
and attempt to negotiate an informal resolution to it first. We will contact you at the email address you have provided 
to us; you can contact Universal Orthodontic Lab’s customer service team by emailing us. If after a good faith effort 
to negotiate one of us feels the dispute has not and cannot be resolved informally, the party intending to pursue 
arbitration agrees to notify the other party via email prior to initiating the arbitration. In order to initiate arbitration, 
a claim must be filed with the AAA and the written Demand for Arbitration (available at www.adr.org) provided to the 
other party, as specified in the AAA Rules.</div><br/><br/>

<div><b>Agreement to Arbitrate.</b><br/>
<b>You and Universal Orthodontic Lab mutually agree that any dispute, claim or controversy arising out of or relating 
    to these Terms or the breach, termination, enforcement or interpretation thereof, or to the use of the Universal Lab 
    Platform, the Services, or the Collective Content (collectively, “Disputes”) will be settled by binding arbitration 
    (the “Arbitration Agreement”). If there is a dispute about whether this Arbitration Agreement can be enforced or 
    applies to our Dispute, you and Universal Orthodontic Lab agree that the arbitrator will decide that issue.</b></div><br/><br/>

<div>Exceptions to Arbitration Agreement.<br/>
You and Universal Orthodontic Lab each agree that the following claims are exceptions to the Arbitration Agreement 
and will be brought in a judicial proceeding in a court of competent jurisdiction: (i) Any claim related to actual or 
threatened infringement, misappropriation or violation of a party’s copyrights, trademarks, trade secrets, patents, 
or other intellectual property rights; (ii) Any claim seeking emergency injunctive relief based on exigent circumstances 
(e.g., imminent danger or commission of a crime, hacking, cyber-attack).<br/><br/></div>

<div>Arbitration Rules and Governing Law.<br/>
This Arbitration Agreement evidences a transaction in interstate commerce and thus the Federal Arbitration Act governs 
the interpretation and enforcement of this provision. The arbitration will be administered by AAA in accordance 
with the Consumer Arbitration Rules and/or other AAA arbitration rules determined to be applicable by the AAA 
(the “AAA Rules“) then in effect, except as modified here. The AAA Rules are 
available at <a href="https://www.adr.org/" target="_blank" rel="noreferrer">www.adr.org</a> or by calling the AAA at 1–800–778–7879.</div><br/><br/>

<div>Arbitration Hearing/Location.<br/>
In order to make the arbitration most convenient to you, Universal Orthodontic Lab agrees that any required arbitration 
hearing may be conducted, at your option, (a) in the county where you reside; (b) in Alameda County; (c) in any other 
location to which you and Universal Orthodontic Lab both agree; (d) via phone or video conference; or (e)for any claim 
or counter claim under $25,000, by solely the submission of documents to the arbitrator.</div><br/><br/>

<div>Attorney’s Fees and Costs.<br/>
Each party will pay the fees for his, her or its own attorneys, subject to any remedies to which that party may later 
be entitled under applicable law (i.e., a party prevails on a claim that provides for the award of reasonable attorney 
fees to the prevailing party). In all cases where required by law, Universal Orthodontic Lab will pay the arbitrator’s 
and arbitration fees. If under applicable law Universal Orthodontic Lab is not required to pay all of the arbitrator’s 
and/or arbitration fees, such fee(s) will be apportioned equally between the parties or as otherwise required by applicable 
law. However, you will not be required to bear any type of fee or expense that you would not be required to bear if you had 
filed the action in a court of law. Any disputes in that regard will be resolved by the arbitrator as soon as practicable
 after the arbitrator is selected, and Universal Orthodontic Lab shall bear all of the arbitrator’s and arbitration fees 
 until such time as the arbitrator resolves any such dispute.</div><br/><br/>

 <div>Arbitrator’s Decision.<br/>
 The arbitrator’s decision will include the essential findings and conclusions upon which the arbitrator based the award. 
 Judgment on the arbitration award may be entered in any court with proper jurisdiction. The arbitrator may award 
 declaratory or injunctive relief only on an individual basis and only to the extent necessary to provide relief warranted 
 by the claimant’s individual claim.</div><br/><br/>

 <div><b>Jury Trial Waiver.</b></div><br/>
 <div><b>You and Universal Orthodontic Lab acknowledge and agree that we are each waiving the right to a trial 
     by jury as to all arbitrable Disputes.</b></div><br/><br/>

<div><b>No Class Actions or Representative Proceedings.</b></div><br/>
<div><b>You and Universal Orthodontic Lab acknowledge and agree that we are each waiving the right to participate 
    as a plaintiff or class member in any purported class action lawsuit, class-wide arbitration, private attorney-general 
    action, or any other representative proceeding as to all Disputes. Further, unless you and Universal Orthodontic Lab 
    both otherwise agree in writing, the arbitrator may not consolidate more than one party’s claims and may not 
    otherwise preside over any form of any class or representative proceeding. If this paragraph is held unenforceable 
    with respect to any Dispute, then the entirety of the Arbitration Agreement will be deemed void with respect 
    to such Dispute.</b></div><br/><br/>

<div>Severability.<br/>
Except as provided in this section, in the event that any portion of this Arbitration Agreement is deemed illegal or 
unenforceable, such provision shall be severed and the remainder of the Arbitration Agreement shall be given full force 
and effect.</div><br/><br/>

<div>Changes.<br/>
Notwithstanding the provisions regarding modification of these Terms, if Universal Orthodontic Lab changes this section 
(“Dispute Resolution and Arbitration Agreement”) after the date you last accepted these Terms (or accepted any subsequent 
changes to these Terms), you may reject any such change by sending us written notice (including by email) within thirty 
(30) days of the date such change became effective, as indicated in the “Last Updated” date above or in the date of 
Universal Orthodontic Lab’s email to you notifying you of such change. By rejecting any change, you are agreeing that 
you will arbitrate any Dispute between you and Universal Orthodontic Lab in accordance with the provisions of the 
“Dispute Resolution and Arbitration Agreement” section as of the date you last accepted these Terms (or accepted any 
subsequent changes to these Terms).</div><br/><br/>

<div>Survival.<br/>
This section will survive any termination of these Terms and will continue to apply even if you stop using the Universal 
Orthodontic Lab Platform or terminate your Universal Orthodontic Lab Account.</div><br/><br/>

<div>General Provisions<br/>
Except as they may be supplemented by additional terms and conditions, policies, guidelines or standards, 
these Terms constitute the entire Agreement between Universal Orthodontic Lab and you pertaining to the subject matter 
hereof, and supersede any and all prior oral or written understandings or agreements between Universal Orthodontic Lab 
and you in relation to the access to and use of the Universal Orthodontic Lab Platform.<br/>

No joint venture, partnership, employment, or agency relationship exists between you and Universal Orthodontic Lab 
as a result of this Agreement or your use of the Universal Orthodontic Lab Platform.<br/>

These Terms do not and are not intended to confer any rights or remedies upon any person other than the parties.<br/>

If any provision of these Terms is held to be invalid or unenforceable, such provision will be struck and will not affect 
the validity and enforce ability of the remaining provisions.<br/>

Universal Orthodontic Lab’s failure to enforce any right or provision in these Terms will not constitute a waiver of 
such right or provision unless acknowledged and agreed to by us in writing. Except as expressly set forth in these Terms, 
the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies 
under these Terms or otherwise permitted under law.<br/>

You may not assign, transfer or delegate this Agreement and your rights and obligations here under without 
Universal Orthodontic Lab’s prior written consent. Universal Orthodontic Lab may without restriction assign, transfer or 
delegate this Agreement and any rights and obligations hereunder, at its sole discretion, with 30 days prior notice. 
Your right to terminate this Agreement at any time remains unaffected.<br/>

If your Country of Residence is the United States, these Terms will be interpreted in accordance with the laws of 
the State of California and the United States of America, without regard to conflict-of-law provisions. Judicial proceedings 
(other than small claims actions) that are excluded from the arbitration agreement section must be brought in state or 
federal court in Los Angeles County, California, unless we both agree to some other location. You and we both consent 
to venue and personal jurisdiction in Los Angeles County, California.<br/>

Unless specified otherwise, any notices or other communications to Users permitted or required under this Agreement, 
will be provided electronically and given by Universal Orthodontic Lab via email, Universal Lab Platform notification, 
or messaging service (including SMS and WeChat).<br/>

If you have any questions about these Terms please get 
in touch with us at <a href="mailto:customerservice@uniortholab.com">customerservice@uniortholab.com</a>.</div>
        <br/><br/><br/>    
            </div>
        );
    }
}

export default TermsAndService;
